// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package week04

import (
	"github.com/iwinder/geekGoWork/internal/pkg/options"
	"github.com/iwinder/geekGoWork/internal/week04/biz"
	"github.com/iwinder/geekGoWork/internal/week04/data/mysql"
	"github.com/iwinder/geekGoWork/internal/week04/service"
)

// Injectors from write.go:

func InitUserServer(opts *configs.MysqlOption) *service.UserService {
	datastore := mysql.NewMySQLDB(opts)
	userRepo := mysql.NewUserRepo(datastore)
	userBiz := biz.NewUserBiz(userRepo)
	userService := service.NewUserService(userBiz)
	return userService
}
